In [122]:
import pandas as pd
import numpy as np

In [123]:
def read_orders (n_clients, path="D:/胡曼婷文件/OneDrive/cours/ESGF 2019/Machine Learning/instacart_market/orders.csv"):
    orders_df = pd.read_csv(path,engine='python')
    orders_df = orders_df[['order_id','user_id']]
    return orders_df[orders_df['user_id'].isin(range(N+1))]

In [124]:
def read_orders_products(path="D:/胡曼婷文件/OneDrive/cours/ESGF 2019/Machine Learning/instacart_market/order_products__prior.csv"):
    orders_products_df = pd.read_csv(path,engine='python')
    return orders_products_df[['order_id','product_id']]

In [125]:
#Number of clients
N =1000
orders_df = read_orders(N)

In [126]:
print(orders_df)

       order_id  user_id
0       2539329        1
1       2398795        1
2        473747        1
3       2254736        1
4        431534        1
5       3367565        1
6        550135        1
7       3108588        1
8       2295261        1
9       2550362        1
10      1187899        1
11      2168274        2
12      1501582        2
13      1901567        2
14       738281        2
15      1673511        2
16      1199898        2
17      3194192        2
18       788338        2
19      1718559        2
20      1447487        2
21      1402090        2
22      3186735        2
23      3268552        2
24       839880        2
25      1492625        2
26      1374495        3
27       444309        3
28      3002854        3
29      2037211        3
...         ...      ...
16115    693984      999
16116   1709731      999
16117   3077221      999
16118   2449134      999
16119    643911      999
16120   2466821      999
16121    922940      999
16122   1083184      999


In [127]:
#read orders_product realation. got ['order_id','product_id']
orders_products_df = read_orders_products()

In [128]:
print(orders_products_df)

          order_id  product_id
0                2       33120
1                2       28985
2                2        9327
3                2       45918
4                2       30035
5                2       17794
6                2       40141
7                2        1819
8                2       43668
9                3       33754
10               3       24838
11               3       17704
12               3       21903
13               3       17668
14               3       46667
15               3       17461
16               3       32665
17               4       46842
18               4       26434
19               4       39758
20               4       27761
21               4       10054
22               4       21351
23               4       22598
24               4       34862
25               4       40285
26               4       17616
27               4       25146
28               4       32645
29               4       41276
...            ...         ...
32434459

In [129]:
#merge 1. got ['user_id','order_id','product_id']
orders_products_df = pd.merge(orders_df,orders_products_df, on='order_id')

In [130]:
def read_products(path="D:/胡曼婷文件/OneDrive/cours/ESGF 2019/Machine Learning/instacart_market/products.csv"):
    products_df = pd.read_csv(path, engine = 'python')
    return products_df[['product_id','department_id']]

In [131]:
products_df = read_products()

In [132]:
#merge 2 got ['user_id, order_id','product_id','department_id']
orders_products_df = pd.merge(orders_products_df, products_df, on='product_id')

In [133]:
data = orders_products_df
print(data)

        order_id  user_id  product_id  department_id
0        2539329        1         196              7
1        2398795        1         196              7
2         473747        1         196              7
3        2254736        1         196              7
4         431534        1         196              7
5        3367565        1         196              7
6         550135        1         196              7
7        3108588        1         196              7
8        2295261        1         196              7
9        2550362        1         196              7
10       2968173       15         196              7
11       1870022       15         196              7
12       1911383       15         196              7
13       2715276       15         196              7
14        487368       15         196              7
15       2293453       19         196              7
16       1973799       19         196              7
17        532817       19         196         

In [134]:
#Browse orders by client.
for client in orders_products_df.groupby("user_id"):
    for order in client[1].groupby("order_id"):
        print(order)
    print("\n")
    break
        

(431534,       order_id  user_id  product_id  department_id
4       431534        1         196              7
202     431534        1       12427             19
266     431534        1       10258             19
274     431534        1       13176              4
2150    431534        1       25133             16
2319    431534        1       10326              4
2339    431534        1       17122              4
2386    431534        1       41787              4)
(473747,       order_id  user_id  product_id  department_id
2       473747        1         196              7
200     473747        1       12427             19
264     473747        1       10258             19
2148    473747        1       25133             16
2187    473747        1       30450             13)
(550135,       order_id  user_id  product_id  department_id
6       550135        1         196              7
204     550135        1       12427             19
268     550135        1       10258             19
21

In [135]:
# List of list of int
L = []

def data_final():    
    #Browse orders by client.
    for user in data.groupby("user_id"):
        user_id = user[0]
        user_data = user[1]
        sequences_user = []
        #orders data for current client
        for order in user_data.groupby("order_id"):
            
            #order 
            order_id = order[0]
            order_data = order[1]
            
            #categories
            department_ids =list(order_data["department_id"])
            
            #keep categories
            sequences_user.append(department_ids)
            #order_ids = [order_id, department_ids]
            #client_ids = [client_id , order_ids]
            #L.append(client_ids)
        L.append(sequences_user)
    return L
        

In [136]:
L = data_final()

In [137]:
print(len(L))

1000


In [147]:
X = np.zeros((1000,3,8)) #100 clients, 3nb pannier, 8 nb d'achat

In [148]:
from keras.preprocessing.sequence import pad_sequences

In [149]:
T=4 #(timestep) On commence avec 4 achats car Il y a un achat à chaque fois et donc pas de 0

for i in range(len(L)): 
    panier =pad_sequences(L[i], maxlen=T, dtype="int32", padding="post", truncating='pre', value=0.0)
    print(panier)

[[16  4  4  4]
 [19 19 16 13]
 [19 19 14 16]
 [19 17 19 16]
 [19 16  7 16]
 [19 19  4 14]
 [16 19 19 17]
 [ 7 19 16 16]
 [19 16  7 16]
 [ 7 19 19 16]]
[[20  1  1  1]
 [ 7  1  4 13]
 [ 4 16 13  1]
 [16 16 16 16]
 [ 1  6 19 20]
 [16 16  1  6]
 [16 19 19 20]
 [11 16 16 16]
 [ 1  1  1  1]
 [ 4 20 16 20]
 [20 20  4  4]
 [19 13 13  3]
 [19 16 16 16]
 [19  4  4  3]]
[[16 17  4  7]
 [16 16  4  4]
 [16 19  9  7]
 [ 4  4 19 19]
 [ 4 19  7  9]
 [ 1  4  4  9]
 [13 16  4  4]
 [13 19  1  1]
 [16  4 16  4]
 [ 4  4 20 19]
 [ 4 16  4  1]
 [ 4  9 13  1]]
[[ 5  7  0  0]
 [15  7  3  1]
 [ 5 17  0  0]
 [19 20 20  0]
 [ 3  7  1 17]]
[[ 4 16 15 16]
 [ 4 13 19  4]
 [ 4  1  1  4]
 [ 4 16  4 16]]
[[15  4 16 13]
 [15 16  4  0]
 [ 4  4 12  4]]
[[ 4  4  4 16]
 [16 15  1 16]
 [ 7  7 20 19]
 [ 7 16 12 19]
 [12  7 19 16]
 [ 4  0  0  0]
 [12  7  4  4]
 [16  7  4 16]
 [ 4 19 16  0]
 [ 4  7 16 16]
 [19  4  4 16]
 [ 4 19 19  4]
 [ 7 16  4  4]
 [19  4  1 16]
 [ 7  7 20 13]
 [13 13 13 15]
 [ 4  7 16  4]
 [ 7  8  4  1]
 [ 7

 [ 4  1 16  1]]
[[ 9 16 11  1]
 [ 4  4 19  1]
 [19  4 16  1]
 [15 12  6  6]]
[[ 7 17 11  0]
 [16 17  0  0]
 [ 4  0  0  0]
 [ 4 17 11  0]
 [17 13  7  0]
 [ 7  4 16  0]
 [17 13  0  0]
 [16 13  0  0]
 [16 17 13  0]
 [ 7 17  6  0]
 [ 7  6  0  0]
 [16 13  0  0]]
[[16  7 17 16]
 [12  5  5 11]
 [16 16  7  7]
 [17 17 16  1]
 [ 4 16 16  1]]
[[ 7  7 13  4]
 [ 4  7  7  4]
 [ 4 13 16  4]
 [ 1  7 16  6]
 [ 4  7 13  7]
 [13 13 13 11]
 [ 7  7  7 13]
 [ 4  7 13  7]
 [ 7  7 11 18]
 [ 7  9  7  7]
 [ 4 12  4  7]
 [16 16  7 19]
 [ 1  1 13  4]
 [ 1 12  4  4]
 [16  4 13 15]
 [19 16 19  7]
 [16  4  4  7]
 [13 19  7  7]
 [16  4 13 14]
 [16  7  4 13]
 [ 7 20  9 13]
 [ 9 15 15 15]
 [ 4 16  7  1]
 [ 4  7  4  4]
 [ 3  4  4 13]
 [ 4 15  7 13]
 [ 4  7 16  7]]
[[ 4 16 13  3]
 [ 4 15  9 19]
 [13  4 17  7]
 [ 9  7  7  9]
 [ 7  7  7 19]]
[[19 17  7 17]
 [ 7 19 11 13]
 [13  7 19  9]
 [13  7 17  9]
 [13  7 19 11]
 [16  7 13  7]
 [16 13 17 19]
 [17 11 13  7]
 [13  7 19  9]
 [17 17 17 17]
 [17  7 19 17]
 [ 7  7 19 11]
 [19

 [13 13 16 13]]
[[ 7  1  1 19]
 [ 4 13 13  7]
 [ 7 15 19 19]
 [ 1 19 19  1]
 [ 1  3 16 16]]
[[16 16 13 16]
 [ 4 13  7  6]
 [ 7  4  3  7]
 [ 4  3  4 20]]
[[16  1  1  1]
 [19 14 14 14]
 [11  1  9 13]
 [ 9 15 15  1]]
[[ 4  4  0  0]
 [ 7 16  4 19]
 [19  1  1 14]
 [19  7  7  1]]
[[ 7 20  7 16]
 [ 7  7 19 16]
 [15 16 19 12]
 [ 7 12 16 16]
 [19 19 18 18]
 [ 4 16 16 16]
 [19  4 12 19]
 [12 16 16  4]
 [ 4 16  4 19]
 [16  7 19 19]
 [16 16 16 18]
 [ 4  4 19 16]
 [ 4  4 16 19]
 [16 13 18 16]
 [ 4 13 16 19]
 [ 4 16 12  0]
 [ 4  4 16  0]
 [ 4 17 16  0]
 [ 4  4  4 16]
 [16 19  7 16]
 [ 4 16 19 19]
 [16 16 19 19]
 [ 7 16 19 19]
 [12 16  4 19]
 [18 16 19 16]
 [ 7 14  7 16]
 [16 19 12 12]
 [16 19 19 19]
 [ 4 16 16 19]
 [16 20  4 16]
 [ 4  4 12 16]
 [ 4 16 19 14]
 [ 4 16 16 16]
 [ 4 16 19 16]
 [ 4 16 16 16]
 [19 16 18 18]
 [18 16 16 18]
 [ 4  4 16 16]
 [ 4 18 17 18]
 [16 16 16 12]
 [16 19 19 19]
 [ 4 19 16 16]
 [ 4 16 12 16]
 [ 4  4 16  0]
 [ 9  4 16 16]
 [ 4  4  4 16]
 [ 7  4  4  0]
 [18 16 18 18]
 [ 4 

 [19 19  1  1]]
[[ 4  4 12  1]
 [16 13 13 16]
 [13  1 16 19]
 [19 19 19  3]
 [ 4  0  0  0]
 [12 13  1 15]
 [19 19 19 19]
 [12 19 16 19]
 [ 4 16  1 16]
 [ 9 19 13 16]
 [17  1 13 10]
 [ 1 19 16  4]
 [16  4 14 16]
 [ 1 16 16 16]
 [ 4 19  3  1]
 [ 9  7  7  7]
 [19 16 13 19]
 [ 4 16 14  1]
 [ 4 19 13 16]
 [19  0  0  0]
 [ 6 13 12 15]
 [ 7  1 13  4]
 [ 6  9  1 13]
 [19 19 19  7]
 [13  1 12 13]
 [13  1 19 20]
 [16  9 16  9]
 [16 15 13  9]]
[[19  7 13 13]
 [16 13 16  3]
 [ 6  4 13  9]
 [16 13 11 13]
 [ 1  1  1  3]
 [ 4 16 16  0]
 [13 13 13 13]
 [ 4 16  4 16]
 [ 1 16  1  1]
 [16  4 16 19]]
[[16 19  5 16]
 [16 16 19 16]
 [19  1 19 19]
 [19 13  3  1]
 [16 13 13 21]
 [13  1 19  7]
 [13 13 13 20]
 [19 16 19 19]
 [13 19 16 19]
 [16  6 16  8]
 [ 1 14 14 19]
 [ 4  6 19 13]
 [16 13 13  1]
 [12 14  3 14]
 [19 19 19 17]
 [ 1 19 19  1]
 [19 16 19  7]
 [17 17 17  3]
 [19 17  7 16]
 [13 19 19 13]
 [ 4 19 19 17]
 [ 1 19 19  7]
 [ 1 11 11  8]
 [ 4 16  1  6]
 [13 12 14 13]
 [17 17 19 12]
 [15 19  5 13]]
[[7 0 

 [ 1 19 15  3]]
[[ 3 16 16 17]
 [16  4 16 19]
 [ 7 16  4 16]
 [16  4 17 19]
 [16 16 16 13]
 [16  4 16 16]
 [14 16 16  4]
 [ 4 16 16 20]
 [12  4 16 15]
 [ 4  1 16 13]
 [15  4 16  1]
 [ 7  4 12 16]
 [ 4 13 13 16]
 [ 4 12  1 16]
 [17 16 16 16]]
[[13 13 15  1]
 [ 4 16  4  1]
 [ 7 19  7 19]
 [ 4 15  0  0]]
[[ 9 14 14  3]
 [ 4 16 16  0]
 [17 13 14 20]
 [ 7  7  9  3]
 [11 20 20 20]
 [16 16 14 20]
 [16 13 14  9]
 [ 7  9 20 20]
 [16 20 20  3]
 [20 20  1 20]
 [ 3 20 20  3]
 [20 16  7  3]
 [11  9 20 20]
 [16 16 11 20]
 [20  7 13  1]
 [13  9  7  3]
 [14  9 20  3]
 [16  9 14 20]
 [16 19 19 16]
 [16  9  7 20]
 [ 9 19  9 20]
 [16 20 14  1]
 [19 13  3  3]
 [ 9 20 20 20]
 [14  9 14 20]
 [16  9  9 20]
 [19 19 16 19]
 [20 20 20  3]
 [ 9 16  9 16]
 [13 20 10  9]
 [14 19 13  3]
 [ 9 13  7 20]
 [13 16  9 20]
 [ 9 13 16  9]
 [14  7 14  3]
 [11  9 20 20]
 [16 16  9 11]
 [ 9  9 20 20]
 [ 7 20 20  3]
 [ 7  3 20 20]
 [ 9  7 11  1]
 [18  9  3 20]
 [ 7 14 18 20]
 [19  7 13 15]
 [ 4  4  4 16]
 [ 9  7 20 20]]
[[19 1

In [151]:
for i in range(len(L)):
    panier =pad_sequences(L[i],maxlen=8,dtype="int32",padding="post",truncating='pre',value=0.0)
    panier=panier[:3]
    X[i]=panier
    

In [152]:
print(X)

[[[ 7. 19. 19. ...  4.  4.  4.]
  [ 7. 19. 19. ...  0.  0.  0.]
  [ 7. 19. 19. ...  0.  0.  0.]]

 [[ 4. 19.  4. ...  1.  1.  1.]
  [16. 19. 20. ...  1.  4. 13.]
  [ 6.  7.  4. ... 16. 13.  1.]]

 [[ 4. 19. 16. ... 17.  4.  7.]
  [ 4. 16. 16. ...  0.  0.  0.]
  [ 4. 16. 16. ...  7.  0.  0.]]

 ...

 [[ 4. 16.  1. ...  0.  0.  0.]
  [ 4. 16. 16. ...  1. 16.  3.]
  [19. 19.  1. ...  3. 15.  4.]]

 [[ 7. 16.  9. ...  7.  1.  1.]
  [ 7. 16. 19. ...  1.  1.  1.]
  [ 1.  3. 16. ...  9.  7. 19.]]

 [[16.  7.  7. ... 16. 16.  7.]
  [ 4.  7.  7. ... 16. 16.  7.]
  [16.  4.  7. ... 16. 20. 16.]]]


In [168]:
Yi = X[:,:,-1]
Xi = X[:,:,:-1]

In [169]:
print(Yi.shape)
print(Xi.shape)

(1000, 3)
(1000, 3, 7)


In [276]:
from numpy import array
from numpy import argmax
from keras.utils import to_categorical
# define example
# one hot encode
Yo = to_categorical(X[:,:,-1])
Yo = Yo.reshape(-1,66)
Xo = X[:,:,:-1]

In [277]:
print(Yo.shape)
print(Xo.shape)

(1000, 66)
(1000, 3, 7)


In [290]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(Xo,Yo,test_size = 0.2, random_state=2)
from keras.preprocessing.sequence import pad_sequences
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
#build the model
model = Sequential()
model.add(LSTM(256,activation='relu', return_sequences=True, input_shape=(Xo.shape[1],Xo.shape[2])))
model.add(LSTM(64, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(66, activation='softmax'))
model.compile(loss='mse', optimizer='adam',metrics=['accuracy'])

In [306]:
model.summary()

callback_1 = keras.callbacks.TensorBoard(log_dir='trainings/t2')
callback_2 = keras.callbacks.EarlyStopping(monitor='val_loss', min_delta=0.0005, patience=5)
#callback_3 = keras.callbacks.ModelCheckpoint(filepath='weights.hdf5', verbose=1, save_best_only=True)

model.fit(X_train, Y_train, epochs=100,batch_size=100,verbose=1, callbacks=[callback_1, callback_2])#, callback_3])




Model: "sequential_28"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_45 (LSTM)               (None, 3, 256)            270336    
_________________________________________________________________
lstm_46 (LSTM)               (None, 64)                82176     
_________________________________________________________________
dropout_22 (Dropout)         (None, 64)                0         
_________________________________________________________________
dense_22 (Dense)             (None, 66)                4290      
Total params: 356,802
Trainable params: 356,802
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
800/800 [==============================] - 0s 540us/step - loss: 0.0244 - accuracy: 0.3650
Epoch 2/100
800/800 [==============================] - 0s 576us/step - loss: 0.0244 - accuracy: 0.3613
Epoch 3/100
800/800 [==================

800/800 [==============================] - 0s 443us/step - loss: 0.0241 - accuracy: 0.2962
Epoch 72/100
800/800 [==============================] - 0s 438us/step - loss: 0.0241 - accuracy: 0.3875
Epoch 73/100
800/800 [==============================] - 0s 443us/step - loss: 0.0241 - accuracy: 0.2862
Epoch 74/100
800/800 [==============================] - 0s 444us/step - loss: 0.0241 - accuracy: 0.3275
Epoch 75/100
800/800 [==============================] - 0s 443us/step - loss: 0.0241 - accuracy: 0.3363
Epoch 76/100
800/800 [==============================] - 0s 446us/step - loss: 0.0241 - accuracy: 0.3288
Epoch 77/100
800/800 [==============================] - 0s 450us/step - loss: 0.0242 - accuracy: 0.2925
Epoch 78/100
800/800 [==============================] - 0s 441us/step - loss: 0.0241 - accuracy: 0.2988
Epoch 79/100
800/800 [==============================] - 0s 443us/step - loss: 0.0241 - accuracy: 0.3250
Epoch 80/100
800/800 [==============================] - 0s 448us/step - loss:

In [314]:
# Accuracy 
loss,accuracy = model.evaluate(X_test,Y_test)
print('loss:%.4f accuracy:%.4f' %(loss,accuracy))

200/200 [==============================] - 0s 374us/step
loss:0.0362 accuracy:0.2000


In [315]:
Yo_true=Y_test.reshape(-1,3,22)

In [316]:
Y_true=np.argmax(Yo_test,axis=1)